blank_issues_enabled: false
contact_links:
  - name: Instructor GitHub
    url: https://github.com/olitreadwell
    about: View the instructor's GitHub profile. For private or urgent questions use the workshop communication channel.
